import type { Property } from "./types"

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Loft",
    price: 850000,
    location: "New York, NY",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    image: "/modern-loft-interior.jpg",
    type: "apartment",
    status: "sale",
  },
  {
    id: "2",
    title: "Luxury Beachfront Villa",
    price: 2500000,
    location: "Miami, FL",
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    image: "/luxury-beach-villa.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "3",
    title: "Contemporary City Apartment",
    price: 3200,
    location: "San Francisco, CA",
    bedrooms: 1,
    bathrooms: 1,
    area: 750,
    image: "/contemporary-apartment.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "4",
    title: "Suburban Family Home",
    price: 650000,
    location: "Austin, TX",
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    image: "/suburban-family-home.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "5",
    title: "Penthouse Suite",
    price: 5500,
    location: "Chicago, IL",
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    image: "/luxury-penthouse.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "6",
    title: "Mountain Retreat Cabin",
    price: 480000,
    location: "Denver, CO",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: "/secluded-mountain-cabin.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "7",
    title: "Urban Studio Loft",
    price: 2100,
    location: "Seattle, WA",
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    image: "/urban-studio-loft.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "8",
    title: "Waterfront Estate",
    price: 3200000,
    location: "Los Angeles, CA",
    bedrooms: 6,
    bathrooms: 5,
    area: 5500,
    image: "/waterfront-estate.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "9",
    title: "Downtown High-Rise",
    price: 4200,
    location: "Boston, MA",
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    image: "/downtown-highrise.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "10",
    title: "Cozy Cottage Home",
    price: 425000,
    location: "Portland, OR",
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: "/cozy-cottage-home.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "11",
    title: "Luxury Condo",
    price: 3800,
    location: "San Diego, CA",
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    image: "/luxury-condo-interior.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "12",
    title: "Historic Brownstone",
    price: 1850000,
    location: "Brooklyn, NY",
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    image: "/historic-brownstone.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "13",
    title: "Modern Townhouse",
    price: 4500,
    location: "Washington, DC",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: "/modern-townhouse.jpg",
    type: "house",
    status: "rent",
  },
  {
    id: "14",
    title: "Lakefront Property",
    price: 1200000,
    location: "Minneapolis, MN",
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    image: "/serene-lakefront-estate.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "15",
    title: "City View Apartment",
    price: 2800,
    location: "Atlanta, GA",
    bedrooms: 1,
    bathrooms: 1,
    area: 850,
    image: "/city-view-apartment.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "16",
    title: "Ranch Style Home",
    price: 580000,
    location: "Phoenix, AZ",
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    image: "/ranch-style-home.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "17",
    title: "Skyline Penthouse",
    price: 8500,
    location: "Miami, FL",
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: "/skyline-penthouse.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "18",
    title: "Garden Villa",
    price: 920000,
    location: "San Jose, CA",
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    image: "/lush-garden-villa.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "19",
    title: "Industrial Loft",
    price: 3500,
    location: "Philadelphia, PA",
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: "/industrial-loft.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "20",
    title: "Colonial Estate",
    price: 1650000,
    location: "Charleston, SC",
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    image: "/colonial-estate.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "21",
    title: "Riverside Apartment",
    price: 2600,
    location: "Nashville, TN",
    bedrooms: 2,
    bathrooms: 1,
    area: 950,
    image: "/riverside-apartment.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "22",
    title: "Mediterranean Villa",
    price: 2100000,
    location: "Santa Barbara, CA",
    bedrooms: 5,
    bathrooms: 5,
    area: 4800,
    image: "/mediterranean-villa.jpg",
    type: "house",
    status: "sale",
  },
  {
    id: "23",
    title: "Smart Home Condo",
    price: 4100,
    location: "Austin, TX",
    bedrooms: 2,
    bathrooms: 2,
    area: 1250,
    image: "/smart-home-condo.jpg",
    type: "apartment",
    status: "rent",
  },
  {
    id: "24",
    title: "Craftsman Bungalow",
    price: 695000,
    location: "Portland, OR",
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    image: "/craftsman-bungalow.jpg",
    type: "house",
    status: "sale",
  },
]
